### ISSUE TITLE
Debugging possible null value

### ISSUE THREAD

**Issue by realflash** [digitickets/terraform-aws-cli#1]
I'd like to use this module to get the IPv6 address of an instance. For spot instances the terraform AWS provider is supposed to provide the address as a data attribute but [it doesn't](https://github.com/hashicorp/terraform-provider-aws/issues/12785)

Here's how I've used it:

    module "get_ipv6_address" {
      source            = "digitickets/cli/aws"
      role_session_name = "GettingIPv6Address"
      aws_cli_commands  = ["ec2", "describe-instances"]
      aws_cli_query     = "Reservations[].Instances[?InstanceId==`$data.aws_instance.spot_instance.id`][].NetworkInterfaces[0].Ipv6Addresses[0].Ipv6Address|[0]"
    }

The CLI query implied by this works nicely on the command line (on the same machine as the same user), and a valid IPv6 address is returned. When I use it with terraform, and try to set a Route 53 record attribute `records` with the output, terraform returns:

`Error: provider.aws: aws_route53_record: webtest.attono.net: "records": required field is not set`

which is from the AWS API, I believe. Using terraform logging I found these line:

    2020/12/14 14:37:30 [INFO] ReferenceTransformer: reference not found: "random_string.awscli_output_temp_file_name"
    2020/12/14 14:37:30 [INFO] ReferenceTransformer: reference not found: "path.module"
    2020/12/14 14:37:30 [DEBUG] ReferenceTransformer: "module.ec2_spot.module.get_ipv6_address.local_file.awscli_results_file" references: []
    2020-12-14T14:37:30.123Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/random/3.0.0/linux_amd64/terraform-provider-random_v3.0.0_x5 pid=18556
    2020-12-14T14:37:30.123Z [DEBUG] plugin: plugin exited
    2020/12/14 14:37:30 [WARN] Provider "registry.terraform.io/hashicorp/local" produced an unexpected new value for module.ec2_spot.module.get_ipv6_address.local_file.awscli_results_file during refresh.
      - Root resource was present, but now absent
    2020/12/14 14:37:30 [WARN] Provider "registry.terraform.io/hashicorp/local" produced an invalid plan for module.ec2_spot.module.get_ipv6_address.local_file.awscli_results_file, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .file_permission: planned value cty.StringVal("0777") does not match config value cty.NullVal(cty.String) 

Also this:

    2020-12-14T14:37:38.602Z [DEBUG] plugin.terraform-provider-external_v2.0.0_x5: 2020/12/14 14:37:38 [TRACE] JSON output: {"output_file":".terraform/modules/ec2_spot.get_ipv6_address/temp/YvupjpBF7mw04Y5L.json"}

The file referenced just contains `null`.

Could you help with debugging further? I can provide the entire Terraform log via some private mechanism if it helps.

**Comment by rquadling** [comment]
It looks like the local file was not produced.

Are you running this locally using Terraform? If so, can you check the tmp directory within the module?

I create ...

```hcl
resource "local_file" "awscli_results_file" {
  depends_on           = [random_string.awscli_output_temp_file_name]
  filename             = "${path.module}/temp/${random_string.awscli_output_temp_file_name.result}.json"
  directory_permission = "0777"
}
```

Can you look in the temp directory within the module to see if any file was created?

Also, how are you planning and applying? I use `terraform apply -auto-approve terraform.tfplan` (in the Makefile for local and my pipeline for automatic).

**Comment by rquadling** [comment]
Oh. If the value can be null, then you'll need to handle that in your assignment.

Also, what version of the local provider are you using?

**Comment by rquadling** [comment]
Also, https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ipv6_addresses suggests the addresses are exported, and so you should be able to get to the addresses of the instance you want.

Can you show me the resource where you are getting the value from the module?

**Comment by rquadling** [comment]
also, can you try ...
```
aws_cli_query     = "Reservations[].Instances[?InstanceId==`${data.aws_instance.spot_instance.id}`][].NetworkInterfaces[0].Ipv6Addresses[0].Ipv6Address|[0]"
```

**Comment by realflash** [comment]
You're right that it AWS provider docs do suggest that it should be possible to get at this, but see [this bug](https://github.com/hashicorp/terraform-provider-aws/issues/12785) which means that you can't. Thus using this module as a workaround.

It looks like I am the plonker who forgot to put in the curly brackets. Adding the brackets into my variable substitution in the query makes it work. Thanks for your help!

**Comment by rquadling** [comment]
More than welcome. And thank you for taking the time to report the issue and reaching out.
